#!/usr/bin/env node
/**
 * Regenerates the list of real top-level domains used to check email addresses.
 *
 * HubSpot refuses any email whose domain doesn't end in a top-level domain on
 * IANA's list, so the site checks the same list before it gets that far: the
 * Worker before charging a card, the theme before the payment step. The two
 * are built separately and can't share a file, so this writes both copies from
 * one download.
 *
 *   node scripts/update-tlds.mjs
 *
 * IANA adds and retires domains a few times a year. Rerun this when a real
 * address is refused, then commit both files.
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SOURCE = 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const targets = [
  'workers/src/tlds.js',
  'hubspot-theme/src/theme/rainy-day-merch/utils/tlds.js',
];

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`IANA list download failed: HTTP ${response.status}`);
const text = await response.text();

const version = text.split('\n')[0].replace(/^#\s*/, '');
const tlds = text
  .split('\n')
  .map((line) => line.trim().toLowerCase())
  .filter((line) => line && !line.startsWith('#'));

if (tlds.length < 1000) throw new Error(`Only ${tlds.length} domains in the download; refusing to write.`);

const file = `/**
 * Real top-level domains, from ${SOURCE}
 * ${version}
 *
 * Generated by scripts/update-tlds.mjs. Don't edit by hand: rerun the script.
 */

export const TLDS = new Set(
  '${tlds.join(' ')}'.split(' ')
);
`;

for (const target of targets) {
  await writeFile(join(root, target), file);
  console.log(`wrote ${target} (${tlds.length} domains)`);
}
